USE EMPRESA 
--1
--Bajar los salarios un 5% a todos los empleados con comisión.
--PARA VER LA TABLA ANTE DE MODIFICARLA
SELECT * FROM TEMPLE WHERE COMIS IS NOT NULL
BEGIN TRANSACTION
UPDATE TEMPLE SET SALAR = SALAR - (SALAR  * 0.05) WHERE
COMIS IS NOT NULL
--PARA VER COMO HA QUEDADO
SELECT * FROM TEMPLE WHERE COMIS IS NOT NULL
ROLLBACK TRANSACTION

--2
--Actualiza los presupuestos de todos los departamentos multiplicándolos por 10.
BEGIN TRANSACTION
SELECT * FROM TDEPTO
UPDATE TDEPTO SET PRESU = PRESU * 10
SELECT * FROM TDEPTO
ROLLBACK TRANSACTION

--3
--Borrar a uno de los empleados nuevos. (Conocemos su nombre)
BEGIN TRANSACTION
SELECT * FROM TEMPLE
DELETE FROM TEMPLE WHERE NOMEM LIKE '%OLIVER%'
SELECT * FROM TEMPLE
ROLLBACK TRANSACTION