--1
--Crea una base de datos llamada FACTURACION.
CREATE DATABASE FACTURACION
USE FACTURACION

--2
--Utiliza el lenguaje de definición de datos de SQL para la creación de las siguientes tabla:
--CLIENTE, FACTURA, ARTICULO, DET_FACTURA
CREATE TABLE CLIENTE (
ID INT IDENTITY (1,1),
NOMBRE VARCHAR(20),
DIRECCION VARCHAR(25),
FECNACIM DATE,
TELEFONO INT,
CORREO VARCHAR(15))
--DROP TABLE CLIENTE
SELECT * FROM CLIENTE

CREATE TABLE FACTURA (
IDFACTURA INT IDENTITY (1,1),
IDCLIENTE INT,
FECHA DATE,
NUMPAGO INT)
SELECT * FROM FACTURA

CREATE TABLE MODO_PAGO(
NUMPAGO INT NOT NULL,
NOMBRE VARCHAR(10),
DETALLES VARCHAR(40))
--DROP TABLE MODO_PAGO

CREATE TABLE DETALLE(
NUMDETALLE INT,
IDFACTURA INT,
IDARTICULO INT, 
CANTIDAD INT,
PRECIO INT,
CONSTRAINT RES6 PRIMARY KEY (NUMDETALLE, IDFACTURA))
--DROP TABLE DETALLE

CREATE TABLE ARTICULO (
IDARTICULO INT PRIMARY KEY,
NOMBRE VARCHAR(20),
PRECIO INT,
STOCK INT,
IDCATEGORIA VARCHAR(10))
--DROP TABLE ARTICULO

CREATE TABLE CATEGORIA(
IDCATEGORIA VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(10),
DESCRIPCION VARCHAR(40))

--SELECT * FROM CLIENTE, FACTURA, DETALLE, MODO_PAGO, ARTICULO, CATEGORIA
--ALTER TABLE FACTURA DROP COLUMN IDARTICULO

--3
--En cada tabla debes definir la clave primaria.
ALTER TABLE CLIENTE ADD CONSTRAINT RES1 PRIMARY KEY(ID)
ALTER TABLE FACTURA ADD CONSTRAINT RES2 PRIMARY KEY(IDFACTURA)
ALTER TABLE MODO_PAGO ADD CONSTRAINT RES3 PRIMARY KEY(NUMPAGO)

--4
--En las tablas con claves foráneas debes hacer la definición
-- en la sentencia de creación de las tablas indicando las reglas de la modificación 
--y de la eliminación.
ALTER TABLE FACTURA ADD CONSTRAINT RES4 FOREIGN KEY (IDCLIENTE)
REFERENCES CLIENTE (ID) ON DELETE SET NULL ON UPDATE CASCADE 
ALTER TABLE FACTURA ADD CONSTRAINT RES5 FOREIGN KEY (NUMPAGO)
REFERENCES MODO_PAGO (NUMPAGO) ON DELETE SET NULL ON UPDATE CASCADE 

ALTER TABLE DETALLE ADD CONSTRAINT RES7 FOREIGN KEY (IDARTICULO)
REFERENCES ARTICULO (IDARTICULO) ON DELETE SET NULL ON UPDATE CASCADE

ALTER TABLE ARTICULO ADD CONSTRAINT RES8 FOREIGN KEY (IDCATEGORIA)
REFERENCES CATEGORIA (IDCATEGORIA) ON DELETE SET NULL ON UPDATE CASCADE

--ALTER TABLE FACTURA DROP CONSTRAINT RES5, RES4

--5
--Para la tabla ARTICULO utiliza “IDENTITY”.
--ALTER TABLE ARTICULO ADD CONSTRAINT RES9 IDENTITY FOR IDARTICULO
ALTER TABLE ARTICULO ADD VECES_VENDIDO INT IDENTITY

--6
--Para la tabla CLIENTE utiliza DEFAULT.
ALTER TABLE CLIENTE ADD CIUDAD VARCHAR(10) DEFAULT 'MALAGA'
SELECT * FROM CLIENTE

--7
--Para la el dni del CLIENTE utiliza: UNIQUE Y CHECK.
ALTER TABLE CLIENTE ADD DNI VARCHAR(9) UNIQUE
CONSTRAINT RES9 CHECK (DNI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')
--ALTER TABLE CLIENTE DROP COLUMN DNI
--ALTER TABLE CLIENTE DROP CONSTRAINT RES6

--8
--Para el sexo de CLIENTE, el stock de ARTICULO y cantidad de DET_FACTURA: CHECK.
ALTER TABLE CLIENTE ADD SEXO VARCHAR(1) CONSTRAINT RES10 CHECK (SEXO LIKE 'F' OR SEXO LIKE 'M')
ALTER TABLE ARTICULO ADD CONSTRAINT RES11 CHECK (STOCK BETWEEN 1 AND 1000)
ALTER TABLE DETALLE ALTER COLUMN CANTIDAD ADD CONSTRAINT RES12 CHECK (CANTIDAD > 0)
--ALTER TABLE DETALLE ALTER COLUMN CANTIDAD INT CHECK CANTIDAD > 0

--9
--Para el la fecha de FACTURA: DEFAULT.
ALTER TABLE FACTURA ADD CONSTRAINT RES12 DEFAULT CURRENT_TIMESTAMP FOR FECHA

--10
--Crea índices en los campos sobre las que pienses que se van a realizar búsquedas.
CREATE INDEX INDICE1 ON CLIENTE (DNI)
CREATE INDEX INDICE2 ON MODO_PAGO (NOMBRE)

--11
--Introduce datos en las tablas. Crea dos vistas. Consúltalas y modifica datos de estas.
-- Compruebas que la modificación se realiza también sobre la tabla original.
SELECT * FROM CLIENTE
INSERT INTO CLIENTE (NOMBRE, DIRECCION, FECNACIM, TELEFONO, CORREO, CIUDAD, DNI, SEXO)
VALUES ('ANTONIO PERES', 'C/LOS HUNDIDOS 32', '1983-11-11', 638281942, 'ANONIN@GMAL.COM', 'MALAGA', '84029348X', 'M')
INSERT INTO CLIENTE (NOMBRE, DIRECCION, FECNACIM, TELEFONO, CORREO, CIUDAD, DNI, SEXO) VALUES 
('ISA DOMINGUEZ', 'C/MERENGUE 2', '1943-01-11', 84729758, 'ISA@GMAIL.COM', 'MALAGA', '84920345H', 'F'),
('MIGUEL DOLORS', 'C/BARANCO', '1976-07-01', 849284521, 'MIGUE@GMAL.COM', 'ALMERIA', '09482452U', 'M'),
('LARA CLARA', 'C/FRANCIA 5', '1995', 849323451, 'LARAN@GMAL.COM', 'CORDOBA', '77733423O', 'F')

--CREAR VISTA
CREATE VIEW VER_CIUDAD AS
SELECT * FROM CLIENTE WHERE CIUDAD LIKE 'MALAGA'
SELECT * FROM VER_CIUDAD

CREATE VIEW VER_CORREOS AS
SELECT CORREO FROM CLIENTE
SELECT * FROM VER_CORREOS

--MODIFICAR VISTA
SELECT CIUDAD FROM VER_CIUDAD UPDATE VER_CIUDAD SET CIUDAD = 'LOCAL' WHERE CIUDAD LIKE 'MALAGA'
--COMPROBACIÓN REALIZADA, LAS MODIFICACIONES SE HAN REALIZADO EN LA TABLA DE ORIGEN
SELECT * FROM CLIENTE

--11
--Añadas, borres y modifiques alguna columna.
ALTER TABLE CLIENTE ADD CLIENTE_PREFERIDO VARCHAR(1)
SELECT * FROM CLIENTE
ALTER TABLE CLIENTE DROP COLUMN CLIENTE_PREFERIDO
SELECT * FROM CLIENTE
BEGIN TRANSACTION 
UPDATE CLIENTE SET CIUDAD = 'MALAGA'
WHERE CIUDAD = 'LOCAL'
SELECT CIUDAD FROM CLIENTE
ROLLBACK TRANSACTION 

--12
--Añadas y borres alguna restricción.
--ALTER TABLE FACTURA DROP CONSTRAINT RES5, RES4