--indicar la base de datos que vamos a usar
USE EJEMPLOEMPRESA
--

SELECT * FROM DEPARTAMENTO

SELECT NOMEM FROM EMPLEADO
WHERE NUMDE > (SELECT NUMDE FROM DEPARTAMENTO WHERE NOMDE = 'Contabilidad')

SELECT NOMEM FROM EMPLEADO E, DEPARTAMENTO D
WHERE D.NOMDE='DEP3' AND E.NUMDE >= D.NUMDE

--Obtener el nombre de cada empleado junto con el nombre del departamento al que pertenece
SELECT NOMEM, NOMDE FROM EMPLEADO E, DEPARTAMENTO D
WHERE E.NUMDE IN 
(SELECT NUMDE FROM DEPARTAMENTO WHERE E.NUMDE = D.NUMDE)

SELECT NOMEM, NOMDE FROM EMPLEADO E, DEPARTAMENTO D
WHERE E.NUMDE = D.NUMDE

SELECT NOMEM, NOMDE FROM DEPARTAMENTO D INNER JOIN EMPLEADO E ON (D.NUMDE =  E.NUMDE)

SELECT NOMEM, NOMDE FROM DEPARTAMENTO D JOIN EMPLEADO E ON (D.NUMDE =  E.NUMDE)

--Saca a todos los empleados aunque no tengan asignado departamento (IS NULL)
SELECT NOMEM, NOMDE FROM DEPARTAMENTO D RIGHT JOIN EMPLEADO E ON (D.NUMDE =  E.NUMDE)

--Saca a todos los empleados aunque no tengan asignado departamento (IS NULL)
SELECT NOMEM, NOMDE FROM DEPARTAMENTO D LEFT JOIN EMPLEADO E ON (D.NUMDE =  E.NUMDE)

SELECT NOMEM, NOMDE FROM DEPARTAMENTO D FULL JOIN EMPLEADO E ON (D.NUMDE =  E.NUMDE)