USE EMPRESA

-- AUMENTAR EL SALARIO A LOS EMPLEADOS
SELECT NOMEM, SALAR, (SALAR * 10/100) AS 'AUMENTO SALARIAL'
FROM TEMPLE

--AVERIGUAR LA LONGITUD DE LOS NOMBRES (SE CUANTAN LOS ESPACIOS Y LAS COMAS)
SELECT NOMEM, LEN(NOMEM) AS 'LONGITUD NOMBRE'
FROM TEMPLE

--AVERIGUAR LA FECHA
SELECT FECNA, YEAR(GETDATE()) - YEAR(FECNA) AS 'AÑO' 
FROM TEMPLE

--FUNCIONES COLECTIVAS O DE AGREGADO
SELECT AVG(SALAR) AS 'SALARIO MEDIO' FROM TEMPLE

SELECT COUNT(EXTEL) AS 'EXTENCIONES TELEFONICAS' FROM TEMPLE