USE EMPRESA

SELECT NUMEM, NUMDE, SALAR FROM TEMPLE ORDER BY 2

--Listar para cada departamento, su número (numde) y el máximo salario que se gana dentro de él. 
SELECT NUMDE, MAX(SALAR) AS 'SALARIO MAXIMO DEL DEPART' 
FROM TEMPLE GROUP BY NUMDE

--LA MISMA CONSULTA PERO A CAMBIO HAY QUE SACAR EL NUMERO DE EMPLEADOS DE CADA DEPARTAMENTO
-- CONSULTA SOLO LOS DEPARTAMENTOS CON CODIGO > 100
SELECT NUMDE, COUNT(*) AS 'NUMERO DE EMPLEADOS', MAX(SALAR) AS 'SALARIO MAXIMO DEL DEPART'
FROM TEMPLE WHERE NUMDE > 100 GROUP BY NUMDE

--LISTAR POR CADA SALARIO CUANTOS EMPLEADOS LO GANAN
SELECT SALAR, COUNT(*) AS 'NUM EMPLEADOS CON EL MISMO SALAR' 
FROM TEMPLE GROUP BY SALAR