SELECT * FROM TEMPLE

INSERT TEMPLE (NUMEM, NUMDE, EXTEL, SALAR, COMIS, NOMEM)
VALUES (109, 121, 350, 990, 100, 'MIRIAM BERTINA')

--TAMBIEN SE PODRIÁ ESCRIBIR DE ESTE MODO, SI SE DESEA DEJAR ALGÚN CAMPO SIN VALOR
INSERT TEMPLE (NUMEM, NUMDE, SALAR, NOMEM)
VALUES (103, 90, 1200, 'LARISA MENDEZ')

--O SI SE SABE LOS NOMBRES DE LOS CAMPOS Y SE TIENE QUE INTRODUCIR LOS VALORES DE TODOS LOS CAMPOS
--SE PUEDE HACER DE ESTE MODO
INSERT INTO TEMPLE VALUES
(112, 121, 350, 1983/11/22, 0, 890, NULL, 1, 'MIGUEL AZULEJOS')

--INTRODUCIR VALORES DE UNA TABLA EN OTRA
--PREVIAMENTE LA TAMBLA HA SIDO CREADA, COSA QUE VEREMOS EN OTRO APARTADOS

INSERT INTO TEMPLE2 SELECT * FROM TEMPLE
--COMPROBAMOS AHORA DE QUE LA TABLA TEMPLE2 EXISTE
SELECT * FROM TEMPLE2

--PARA INSERTAR UNA SOLA COLUMNA SE UTILIZA LA SENTENCIA
INSERT INTO TEMPLE2 (MUNDE)
SELECT NUMDE FROM TEMPLE

--INSERTAR LOS VALORES DE ALGUNA SUBCONSULTA
INSERT INTO TEMPLE2 (SALAR)
SELECT SALAR FROM TEMPLE WHERE SALAR >= 1250

--TAMBIEN SE PUEDEN PONER LOS NOMBRES DE LAS COLUMNAS DELANTE DE LA TABLA
SELECT NUMDE, NOMEM, NUMEM INTO TEMPLE2 FROM TEMPLE
WHERE SALAR > (SELECT AVG(SALAR) FROM TEMPLE)
--MOSTRAR RESULTADO
SELECT * FROM TEMPLE2