SELECT * FROM TCENTR

--ACTUALIZAR LA DIRECCIÓN DE LA SEDE CENTRAL
UPDATE TCENTR SET SEÑAS = 'C. MÁLAGA, 21, MADRID'
WHERE NUMCE = 10

SELECT * FROM TEMPLE

--al empleado 400 asígnale un suledo igual al doble del salario más pequeño de su departamento.
UPDATE TEMPLE SET SALAR =
(SELECT MIN(SALAR)*2 FROM TEMPLE E2 WHERE E2.NUMDE = NUMDE)
WHERE NUMEM = 111