SELECT * FROM TCENTR

--DE DONDE EMPIEZA LA TRANZACCIÓN, EL PUNTO DONDE LA CREAMOS
BEGIN TRANSACTION

--ACTUALIZAR LA DIRECCIÓN DE LA SEDE CENTRAL
UPDATE TCENTR SET SEÑAS = 'C. MÁLAGA, 21, MADRID'
WHERE NUMCE = 20

--SI NO QUIEREMOS QUE LAS MODIFICACIONES SE GUARDEN VOLVEMOS DESDE EL PUNTO DE CREACIÓN
ROLLBACK TRANSACTION