USE EMPRESA

SELECT * FROM TEMPLE

--SACAR 'TODOS' LOS EMPLEADOS QUE TIENEN UN SUELDO MAYOR QUE LOS EMPLEADOS DEL DEPARTAMENTO 110
SELECT * FROM TEMPLE WHERE (SALAR > ALL
(SELECT SALAR FROM TEMPLE WHERE NUMDE = 110))

--PODRIAMOS HACERLO DE ESTE MODO TAMBIÉN
SELECT * FROM TEMPLE WHERE (SALAR > 
(SELECT MAX(SALAR) FROM TEMPLE WHERE NUMDE = 110))