USE EMPRESA

SELECT * FROM TEMPLE

--Si existe algún departamento, entonces decir cuantos empleados tiene la empresa
SELECT COUNT(*) AS 'NUMERO EMPLEADOS' FROM TEMPLE WHERE EXISTS
(SELECT * FROM TEMPLE)

--SI NO EXISTE ALGÚN DEPARTAMENTEO, ENTONCE DECIR CUANTOS EMPLEADO TIENE LA EMPRESA
SELECT COUNT(*) AS 'DEPART SIN DIRECTOR' FROM TEMPLE WHERE NOT EXISTS
(SELECT * FROM TDEPTO WHERE TIDIR = 'F')