--NOS CREAMOS LA BASE DE DATOS
CREATE DATABASE PROBANDO

USE PROBANDO

CREATE TABLE JUGADOR1(
NOMBRE VARCHAR(10),
DNI VARCHAR(9),
NUMERO INT IDENTITY (1,1)) --EL NUMERO EMPIEZA EN 1, Y SE INCREMENTA DE 1 EN 1

SELECT * FROM JUGADOR1

INSERT INTO JUGADOR1 VALUES ('JUAN', '78934564X')

--REPETIMOS EL PROCESO PARA VER COMO IDENTITY SE INCREMENTA SOLO
INSERT INTO JUGADOR1 VALUES('LAURA', '23567234H'), ('ANTONIO', '67322387L')

--DECLARANDO UNA COLUMNA PRIMARY KEY
CREATE TABLE JUGADOR2(
NOMBRE VARCHAR(10),
DNI VARCHAR(9) NOT NULL,
NUMERO INT IDENTITY PRIMARY KEY)

SELECT * FROM JUGADOR2

INSERT INTO JUGADOR2 VALUES ('LAURA', '23567234H'), ('ANTONIO', '67322387L')

--TAMBIEN SE PUEDE DECLARAR PRIMARY KEY DE ESTA 2 FORMAS
--FORMA I
CREATE TABLE JUGADOR3(
NOMBRE VARCHAR(10),
DNI VARCHAR(9) NOT NULL,
NUMERO INT,
PRIMARY KEY(NUMERO))

INSERT INTO JUGADOR3 VALUES ('LAURA', '23567234H', 1), ('ANTONIO', '67322387L', 25), ('JUAN', '78934564X', 15)

SELECT * FROM JUGADOR3

--FORMA II
CREATE TABLE JUGADOR4(
NOMBRE VARCHAR(10),
DNI VARCHAR(9) NOT NULL,
NUMERO INT,
CONSTRAINT RESTRICJUGADOR PRIMARY KEY(NUMERO))
--CONSTRAINT ES UNA RESTRICCIÓN QUE SE DECLARA
--RESTRICJUGADOR ES EL NOMBRE QUE LE DAMOS A LA RESTRICCIÓN, SI NO LE DAMOS UNO EL SISTEMA LE ASIGNARA UNO
--POR DEFECTO

INSERT INTO JUGADOR4 VALUES ('LAURA', '23567234H', 1), ('ANTONIO', '67322387L', 25), ('JUAN', '78934564X', 15)

SELECT * FROM JUGADOR4