USE PROBANDO

CREATE TABLE ATLETA(
NUMERO INT PRIMARY KEY,
NOMBRE VARCHAR (20),
DNI VARCHAR (9))

SELECT * FROM ATLETA

--HAY DOS FORMAS DE DECLARAR LA FOREIGN KEY, AL IGUAL QUE LA PRIMARY KEY
--I
CREATE TABLE ABANDONO_ATLETA(
NUMERO INT PRIMARY KEY REFERENCES ATLETA(NUMERO),
NOMBRE VARCHAR (20),
DNI VARCHAR (9))

--II
CREATE TABLE ATLETA_FINALIZADOS(
NUMERO INT FOREIGN KEY REFERENCES ATLETA(NUMERO),
NOMBRE VARCHAR (20),
DNI VARCHAR (9))

SELECT * FROM ABANDONO_ATLETA
SELECT * FROM ATLETA_FINALIZADOS