USE PROBANDO

--CREACIÓN DE TIPO DE DATO
SP_ADDTYPE CIUDAD, 'VARCHAR(30)', 'NOT NULL'

CREATE TABLE ATLETA5(
NUMERO INT PRIMARY KEY,
NOMBRE VARCHAR (20),
DNI VARCHAR (9),
CIUDAD VARCHAR(10) DEFAULT 'MÁLAGA')

--OTROS TIPO DE DEFAULT
CREATE TABLE ATLETAS6(
NUMERO INT DEFAULT 1)

--
CREATE TABLE ATLETAS7(
FECHAPARTICIP DATETIME DEFAULT CURRENT_TIMESTAMP)

--
CREATE TABLE ATLETA8(
FECHAPARTICIP DATETIME DEFAULT GETDATE())

--TAMBIEN PODRIAMOS PONERLE NOMBRE A LA RESTRICCIÓN
--LA RESTRICCIÓN PARA DEFAULT SE DEBE HACER EN LA DEFINICIÓN DEL MISMO CAMPO
CREATE TABLE ATLETA9(
CIUDAD VARCHAR(10) CONSTRAINT RESTRIC6 DEFAULT 'MALAGA')

SELECT * FROM ATLETA9

DROP TABLE ATLETA5, ATLETAS6, ATLETAS7, ATLETA8, ATLETA9