USE PROBANDO

 CREATE TABLE ATLETAS4(
 NOMBRE VARCHAR(10) PRIMARY KEY,
 NUMERO INT)

INSERT INTO ATLETAS4 (nombre, numero)
VALUES('Miguel', 1389),
	 ('Juan', 1736), 
	 ('Eli', 1877), 
	 ('Adrian', 1622), 
	 ('Jesus', 1756), 
	 ('Luis', 2345), 
	 ('Adriana', 2342), 
	 ('Manoli', 1436)

SELECT * FROM ATLETAS4

--COMPROBAMOS LOS ATLETAS QUE SE INSCRIBEN QUE EL NÚMERO INTRODUCIDO CORRESPONDE ENTRE 1 Y 1000
CREATE TABLE ATLETAS5(
NOMBRE VARCHAR(10),
NUMERO INT CHECK (NUMERO BETWEEN 1 AND 1000))

--COMPROBAR UN DNI
CREATE TABLE ATLETAS6(
NOMBRE VARCHAR(10),
DNI VARCHAR(9) CHECK (DNI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'))

--HACER LO MISMO PERO OBLIGANDO EN QUE LA COLUMNA NO SE QUEDE VACIA Y QUE SEA UN DNI UNICO
CREATE TABLE ATLETAS7(
NOMBRE VARCHAR(10),
DNI VARCHAR(9) NOT NULL UNIQUE CHECK (DNI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'))