USE PROBANDO

--COLUMNAS

SELECT * FROM JUGADOR1

--INSERTAR EN LA TABLA UNA NUEVA COLUMNA DONDE SI NO SE ESPECIFICA EL NÚMERO DE 
--PARTICIPACIONES ESTE SE AUTOCOMPLETA
ALTER TABLE JUGADOR1 ADD PARTICIPACIONES INT DEFAULT 1

INSERT INTO JUGADOR1 (NOMBRE, DNI)
VALUES ('ISA', '56789234H')

--NO ACCEPTAR UNA COLUMNA SIN QUE SE LES DECLARE UN VALOR
SELECT * FROM JUGADOR2
ALTER TABLE JUGADOR2 ADD CIUDAD VARCHAR(10) NOT NULL DEFAULT 'MALAGA'

--EN EL EJEMPLO SIGUIENTE SE AGREGA UNA COLUMNA DE TIPO IDENTITY
SELECT * FROM JUGADOR3
--AGREGAREMOS UNA COLUMNA PARA VER EL NÚMERO DE SALIDA EN EL MARATON
ALTER TABLE JUGADOR3 ADD SALIDA_MARATON INT IDENTITY

-----------------------------------------------------

--RESTRICCIONES
SELECT * FROM JUGADOR1

ALTER TABLE JUGADOR1 ADD PARADAS INT 

ALTER TABLE JUGADOR1 WITH NOCHECK
ADD CONSTRAINT RESTRIC CHECK (PARADAS < 5) 

--ALTER TABLE JUGADOR1 DROP CONSTRAINT RESTRIC

--AÑADIR RESTRICCIÓN PRIMARY KEY
ALTER TABLE JUGADOR1 ADD CONSTRAINT RESTRIC6 PRIMARY KEY (NUMERO)

--AÑADIR UNA RESTRICCIÓN FOREIGN KEY
ALTER TABLE JUGADOR2 ADD CONSTRAINT RESTRIC7 FOREIGN KEY (NUMERO)
REFERENCES JUGADOR1 ON DELETE SET NULL ON UPDATE CASCADE 

--AÑADIR UNA RESTRICCIÓN DEFAULT
ALTER TABLE JUGADOR1 ADD CONSTRAINT RESTRIC8 DEFAULT 1 FOR PARADAS