USE PROBANDO

--BORRAR COLUMNAS
SELECT * FROM JUGADOR4

ALTER TABLE JUGADOR4 DROP COLUMN DNI

--BORRAR TABLA
DROP TABLE JUGADOR4

--BORRAR RESTRICCIÓN
ALTER TABLE JUGADOR1 DROP CONSTRAINT RESTRIC