USE EMPRESA

CREATE PROCEDURE P5 @NOMBREDEPARTAMENTO VARCHAR(20) AS BEGIN 
DECLARE @VALORRETORNO INT
EXEC @VALORRETORNO = P4 @NOMBREDEPARTAMENTO
IF (@VALORRETORNO = 1)
	PRINT 'LA MEDIA DE LOS SALARIOS DE LOS DEPARTAMENTOS ' + @NOMBREDEPARTAMENTO + 
	'SUPERA LOS 2000 EUROS' 
ELSE 
	PRINT 'NO LO SUPERA'
END

--COMPROBACIÓN
SELECT D.NOMDE, AVG(SALAR) FROM TDEPTO D JOIN TEMPLE E ON (D.NUMDE = E.NUMDE)
GROUP BY D.NOMDE

--EJECUCIÓN
EXEC P5 'NOMINAS'
EXEC P5 'ORGANIZACION'