--Deseamos saber cuantos empleados tiene un departamento que se pasa como parámetro
USE EMPRESA

CREATE PROCEDURE P3 @NOMBREDEPARTAMENTO VARCHAR (20), @NUMERO INT OUTPUT AS 
SELECT @NUMERO = COUNT(*) FROM TEMPLE E JOIN TDEPTO D ON (E.NUMDE = D.NUMDE)
WHERE D.NOMDE LIKE @NOMBREDEPARTAMENTO

--DROP PROCEDURE P3

--EJECUCIÓN
DECLARE @NUM INT 
EXEC P3 'PERSONAL', @NUM OUTPUT 
PRINT @NUM 