USE FORMACION
--Trigger que controla que cuando se introduzca un código de departamento en la tabla TRABAJADOR
--este código exista en la tabla DEPARTAMENTO o bien este sea nulo.

CREATE TRIGGER TRIG5 ON TRABAJADOR FOR INSERT, UPDATE AS BEGIN 
DECLARE @VALOR INT
SELECT @VALOR = CODDEPTO FROM INSERTED 

IF @VALOR IS NOT NULL 
	IF(SELECT COUNT(*) FROM DEPARTAMENTO WHERE CODDEPTO = @VALOR) = 0
		BEGIN 
		ROLLBACK TRANSACTION 
		PRINT 'CODIGO DE DEPARTAMENTO INEXISTENTE'
	END 
END

SELECT * FROM TRABAJADOR
SELECT * FROM DEPARTAMENTO

UPDATE TRABAJADOR SET CODDEPTO=1000 WHERE CODTRAB=12
UPDATE TRABAJADOR SET CODDEPTO=NULL WHERE CODTRAB=12

INSERT INTO TRABAJADOR VALUES (5000, 'ROCIO','GÁLVEZ ROMERO','12/09/1966',2000,1000,100)
INSERT INTO TRABAJADOR VALUES (5000, 'ROCIO','GÁLVEZ ROMERO','12/09/1966',2000,1,100)