USE FORMACION
--Trigger que controla que cuando borremos un departamento, para todos los empleados
--pertenecientes a él se pongan a NULL CODDEPTO hasta que se les asigne a otro departamento 

CREATE TRIGGER TRIG3 ON DEPARTAMENTO FOR DELETE AS BEGIN 
DECLARE @VALOR INT
SELECT @VALOR = CODDEPTO FROM DELETED 

IF(SELECT COUNT(*) FROM TRABAJADOR WHERE CODDEPTO = @VALOR) > 0
	UPDATE TRABAJADOR SET CODDEPTO = NULL WHERE CODDEPTO = @VALOR 
END

SELECT * FROM DEPARTAMENTO
SELECT * FROM TRABAJADOR

DELETE DEPARTAMENTO WHERE CODDEPTO = 2