USE FORMACION
--Trigger que controla que no se den de alta dos cursos con el mismo nombre

CREATE TRIGGER TRIG2 ON CURSO FOR INSERT AS BEGIN 
DECLARE @VALOR INT, @NOMCURSO VARCHAR(30)
SELECT  @VALOR = CODCURSO, @NOMCURSO = NOMCURSO FROM INSERTED 

IF(SELECT COUNT(*) FROM CURSO WHERE NOMCURSO = @NOMCURSO) > 1
BEGIN
	DELETE CURSO WHERE CODCURSO = @VALOR
END
END

INSERT INTO CURSO VALUES (101,'CISCO',30,'20/04/2012')
INSERT INTO CURSO VALUES (102,'CISCO',30,'20/04/2012')

SELECT * FROM CURSO