USE FORMACION
--Trigger que controla que cuando modifiquemos un codigo de departamento en la tabla DEPARTAMENTO, 
--se modifique en CASCADA en la tabla de TRABAJADORES.

CREATE TRIGGER TRIG4 ON DEPARTAMENTO FOR UPDATE AS BEGIN 
DECLARE @VALORANTIGUO INT
DECLARE @VALORNUEVO INT

SELECT @VALORANTIGUO = CODDEPTO FROM DELETED 
PRINT @VALORANTIGUO
SELECT @VALORNUEVO = CODDEPTO FROM INSERTED 
PRINT @VALORNUEVO

IF(SELECT COUNT(*) FROM TRABAJADOR WHERE CODDEPTO = @VALORANTIGUO) > 0
	UPDATE TRABAJADOR SET CODDEPTO = @VALORANTIGUO WHERE CODDEPTO = @VALORANTIGUO
END 

SELECT * FROM DEPARTAMENTO
SELECT * FROM TRABAJADOR

UPDATE DEPARTAMENTO SET CODDEPTO=33 WHERE CODDEPTO=3