USE FORMACION
--Trigger que controla que no se den de alta dos cursos con el mismo nombre
CREATE TRIGGER TRIG1 ON CURSO FOR INSERT AS
DECLARE @VALOR INT 
SELECT @VALOR = CODCURSO FROM INSERTED 
PRINT @VALOR 
SELECT * FROM INSERTED 

IF (SELECT COUNT(*) FROM CURSO C, INSERTED I WHERE C.NOMCURSO=I.NOMCURSO)>1
BEGIN
    DELETE CURSO WHERE CODCURSO=@VALOR
END

INSERT INTO CURSO VALUES (100,'PROGRAMACIÓN',30,'20/04/2012')
INSERT INTO CURSO VALUES (101,'LENGUAJE MARCAS',30,'20/04/2012')
INSERT INTO CURSO VALUES (102,'ANDROID',30,'20/04/2012')

SELECT * FROM CURSO