use FORMACION
--Trigger que controla que cuando se introduzca un código de departamento en la tabla TRABAJADOR
--este código exista en la tabla DEPARTAMENTO o bien este sea nulo.

CREATE TRIGGER TRIG6 ON TRABAJADOR FOR INSERT, UPDATE AS BEGIN
DECLARE @CODDEPTO INT, @VALOR INT, @CODTRABAJADOR INT, @FILAS INT
SELECT @CODDEPTO = @CODDEPTO, @CODTRABAJADOR = CODTRAB FROM INSERTED 
SELECT @VALOR = CODDEPTO FROM DELETED 

IF @CODDEPTO IS NOT NULL 
	IF(SELECT COUNT(*) FROM DEPARTAMENTO WHERE CODDEPTO = @CODDEPTO) = 0
	BEGIN 
		PRINT 'CODIGO DE DEPARTAMENTO INEXISTENTE'
		SELECT @FILAS = COUNT(*) FROM DELETED 
		PRINT @FILAS 
		IF(@FILAS) = 0
			BEGIN 
			DELETE FROM TRABAJADOR WHERE CODTRAB = @CODTRABAJADOR
			END
		ELSE 
			BEGIN
			PRINT @VALOR
			UPDATE TRABAJADOR SET CODDEPTO = @VALOR WHERE CODTRAB = @CODTRABAJADOR
			END
	END 
END

SELECT * FROM TRABAJADOR
SELECT * FROM DEPARTAMENTO

UPDATE TRABAJADOR SET CODDEPTO=1000 WHERE CODTRAB=3
UPDATE TRABAJADOR SET CODDEPTO=33 WHERE CODTRAB=3

INSERT INTO TRABAJADOR VALUES (400, 'ANDREA','GALAN ROMERO','12/09/1966',2000,1000,100)
INSERT INTO TRABAJADOR VALUES (400, 'ANDREA','GALAN ROMERO','12/09/1966',2000,33,100)